services:
    mailchimp_ecommerce.mailchimp:
        class: Atresmediahf\MailChimpEcommerceBundle\Services\MailChimp
        arguments:
            - %mailchimp_ecommerce.api_key%
            - %mailchimp_ecommerce.store_id%
            - @mailchimp_ecommerce.guzzle_client
            - true

    mailchimp_ecommerce.product:
        class: Atresmediahf\MailChimpEcommerceBundle\Services\ProductService
        arguments:
            - @mailchimp_ecommerce.mailchimp

    mailchimp_ecommerce.customer:
        class: Atresmediahf\MailChimpEcommerceBundle\Services\CustomerService
        arguments:
            - @mailchimp_ecommerce.mailchimp

    mailchimp_ecommerce.order:
        class: Atresmediahf\MailChimpEcommerceBundle\Services\OrderService
        arguments:
            - @mailchimp_ecommerce.mailchimp